version: '3'
services: 
    master:
        image: redis
        container_name: redis-master
        ports: 
        - 6379:6379
    slave1:
        image: redis
        container_name: redis-slave1
        ports: 
        - 6380:6379
        command: redis-server --slaveof redis-master 6379
        depends_on: 
        - master
    slave2:
        image: redis
        container_name: redis-slave2
        ports: 
        - 6381:6379
        command: redis-server --slaveof redis-master 6379
        depends_on: 
        - master
        - slave1
