version: '3'
services: 
    node1:
        container_name: redis-node1
        build: 
            context: redis
            args:
            - REDIS_PORT=9001
        volumes: 
        - ./data/node1/data:/data
        network_mode: host
    node2:
        container_name: redis-node2
        build: 
            context: redis
            args:
            - REDIS_PORT=9002
        volumes: 
        - ./data/node2/data:/data
        network_mode: host
    node3:
        container_name: redis-node3
        build: 
            context: redis
            args:
            - REDIS_PORT=9003
        volumes: 
        - ./data/node3/data:/data
        network_mode: host
    node4:
        container_name: redis-node4
        build: 
            context: redis
            args:
            - REDIS_PORT=9004
        volumes: 
        - ./data/node4/data:/data
        network_mode: host
    node5:
        container_name: redis-node5
        build: 
            context: redis
            args:
            - REDIS_PORT=9005
        volumes: 
        - ./data/node5/data:/data
        network_mode: host
    node6:
        container_name: redis-node6
        build: 
            context: redis
            args:
            - REDIS_PORT=9006
        volumes: 
        - ./data/node6/data:/data
        network_mode: host
    cluster-creator:
        image: redis
        container_name: redis-cluster-creator
        entrypoint: redis-cli --cluster create 192.168.100.4:9001 192.168.100.4:9002 192.168.100.4:9003 192.168.100.4:9004 192.168.100.4:9005 192.168.100.4:9006 --cluster-replicas 1 --cluster-yes
        network_mode: host
        depends_on: 
        - node1
        - node2
        - node3
        - node4
        - node5
        - node6
