version: '3'
services: 
    sentinel1:
        container_name: redis-sentinel1
        image: redis
        volumes: 
        - ./sentinel1.conf:/etc/redis/sentinel/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel/sentinel.conf
        ports: 
        - 26379:26379
    sentinel2:
        container_name: redis-sentinel2
        image: redis
        volumes: 
        - ./sentinel2.conf:/etc/redis/sentinel/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel/sentinel.conf
        ports: 
        - 26380:26379
    sentinel3:
        container_name: redis-sentinel3
        image: redis
        volumes: 
        - ./sentinel3.conf:/etc/redis/sentinel/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel/sentinel.conf
        ports: 
        - 26381:26379
networks: 
    default:
        external: 
            name: master-slave_default
